apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: {{ .Values.appName }}
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.dbAppName }}-config
              key: host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.dbAppName }}-config
              key: port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.dbAppName }}-config
              key: name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbAppName }}-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbAppName }}-secret
              key: password
      restartPolicy: Always
