apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}-service
spec:
  ports:
  - name: {{ .Values.appName }}
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
