apiVersion: v1
kind: Secret
metadata:
  name: app-ingress-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsCert }}
  tls.key: {{ .Values.tlsKey }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  tls:
  - secretName: app-ingress-tls-secret
  rules:
  - host: api.{{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.flaskAPI.appName }}-service
            port:
              name: {{ .Values.flaskAPI.appName }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-help-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/permanent-redirect: {{ .Values.helpUrl | default "https://github.com/ricket-son/PetStore" }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  tls:
  - secretName: app-ingress-tls-secret
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: none
            port:
              name: none