apiVersion: v1
data:
  rootPassword: {{ .Values.dbRootPassword }}
  password: {{ .Values.dbPassword }}
  user: {{ .Values.dbUser }}
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
type: Opaque
